# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c932c0595bc2b50574c48c50aacf909589b063d30f3d731ffefe4f101dbe9fc71b52fffa35a81531109554a560e0f3839a057986bceb8a4b99076b17a9cba38b

test:
  secret_key_base: 6ba184ec61c71b4b737f86a5958a25a16ee278aa2b50c628ec3ce5ae5ae63033cf9181ef128f9c6e5e49453c461a5a92b38c9dd0402b535e525e0e31859cd5a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
